version: "3.9"  # optional since v1.27.0
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=scott_bak
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db

